### ISSUE TITLE
File not found when "Elementum Play" chosen from entry in Kodi Library

### ISSUE THREAD

**Issue by Djtrip83** [elgatito/context.elementum#14]
In the past week Elementum Context keeps showing a "File Not Found" notification when selecting the option "Elementum Play" from any non-Elementum entry I have on the Kodi movie library. This was not happening before. What am I doing wrong?

I am on Kodi 19 for Android.

**Comment by antonsoroko** [comment]
http://elementum.surge.sh/contribute/log/

**Comment by antonsoroko** [comment]
also last release was on May 14, 2021
before that on Mar 16, 2021

so there was no changes in the past week(s).

thus, maybe it is not connected to plugin but to library changes?

**Comment by Djtrip83** [comment]
@antonsoroko here they are:
https://paste.kodi.tv/wunoqijepi (from row 3497 you will find 3-4 instances to check reflecting 3-4 tests)
https://paste.kodi.tv/ukexakisuf

First time I use the log upload feature so let me know if what I loaded is correct.
I am on Matrix 19.1 with the latest release

**Comment by antonsoroko** [comment]
we published new version of context.elementum too early. it uses new paths for api calls.
so it depends on changes in elementum, but new version of elementum was not released yet.

@elgatito do you have plans to make new release of elementum in the near future?

**Comment by Djtrip83** [comment]
in the meantime, which old versions of plugin, burst and context work fine together?
while I wait for the release...

**Comment by antonsoroko** [comment]
Temporary install context 0.0.5

**Comment by Djtrip83** [comment]
Context with 0.05, plugin with 1.71 and burst with 0.62 but the issue persists. I will wait until a new release if that is the solution needed.

**Comment by antonsoroko** [comment]
just checked: 0.0.5 + 0.1.76 works. you might need to restart kodi after installing addons.

**Comment by antonsoroko** [comment]
@Djtrip83 
try with 0.1.77
i mean 0.0.6+0.1.77

**Comment by Djtrip83** [comment]
@antonsoroko managed to make it work with context 0.0.5 and plugin 1.76 yesterday. Will try 1.77 later this week.

**Comment by Djtrip83** [comment]
@antonsoroko 0.06 works with 1.77 and 0.67 burst 👍😁
